routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('users', App\Http\Controllers\UserController::class);


Route::resource('hotelBranches', App\Http\Controllers\HotelBranchController::class);


Route::resource('roomTypes', App\Http\Controllers\RoomTypeController::class);


Route::resource('rooms', App\Http\Controllers\RoomController::class);


Route::resource('taskTypes', App\Http\Controllers\TaskTypeController::class);


Route::resource('tasks', App\Http\Controllers\TaskController::class);


Route::resource('bookings', App\Http\Controllers\BookingController::class);

Route::get('/availablebookroom/{id}/{check_in_date}/{check_out_date}','App\Http\Controllers\BookingController@availablebookroom')->name('availablebookroom');

Route::get('/availablerooms/{check_in_date}/{check_out_date}/{location}','App\Http\Controllers\BookingController@availablerooms')->name('availablerooms');

Route::resource('payments', App\Http\Controllers\PaymentController::class);

Route::get('generatereport/{start_date}/{end_date}/{hotel_id}','App\Http\Controllers\PaymentController@generatereport')->name('generatereport');

app/Http/Controllers/TaskTypeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\TaskTypeDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateTaskTypeRequest;
use App\Http\Requests\UpdateTaskTypeRequest;
use App\Repositories\TaskTypeRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class TaskTypeController extends AppBaseController
{
    /** @var TaskTypeRepository $taskTypeRepository*/
    private $taskTypeRepository;

    public function __construct(TaskTypeRepository $taskTypeRepo)
    {
        $this->taskTypeRepository = $taskTypeRepo;
    }

    /**
     * Display a listing of the TaskType.
     *
     * @param TaskTypeDataTable $taskTypeDataTable
     *
     * @return Response
     */
    public function index(TaskTypeDataTable $taskTypeDataTable)
    {
        return $taskTypeDataTable->render('task_types.index');
    }

    /**
     * Show the form for creating a new TaskType.
     *
     * @return Response
     */
    public function create()
    {
        return view('task_types.create');
    }

    /**
     * Store a newly created TaskType in storage.
     *
     * @param CreateTaskTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateTaskTypeRequest $request)
    {
        $input = $request->all();

        $taskType = $this->taskTypeRepository->create($input);

        Flash::success('Task Type saved successfully.');

        return redirect(route('taskTypes.index'));
    }

    /**
     * Display the specified TaskType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $taskType = $this->taskTypeRepository->find($id);

        if (empty($taskType)) {
            Flash::error('Task Type not found');

            return redirect(route('taskTypes.index'));
        }

        return view('task_types.show')->with('taskType', $taskType);
    }

    /**
     * Show the form for editing the specified TaskType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $taskType = $this->taskTypeRepository->find($id);

        if (empty($taskType)) {
            Flash::error('Task Type not found');

            return redirect(route('taskTypes.index'));
        }

        return view('task_types.edit')->with('taskType', $taskType);
    }

    /**
     * Update the specified TaskType in storage.
     *
     * @param int $id
     * @param UpdateTaskTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTaskTypeRequest $request)
    {
        $taskType = $this->taskTypeRepository->find($id);

        if (empty($taskType)) {
            Flash::error('Task Type not found');

            return redirect(route('taskTypes.index'));
        }

        $taskType = $this->taskTypeRepository->update($request->all(), $id);

        Flash::success('Task Type updated successfully.');

        return redirect(route('taskTypes.index'));
    }

    /**
     * Remove the specified TaskType from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $taskType = $this->taskTypeRepository->find($id);

        if (empty($taskType)) {
            Flash::error('Task Type not found');

            return redirect(route('taskTypes.index'));
        }

        $this->taskTypeRepository->delete($id);

        Flash::success('Task Type deleted successfully.');

        return redirect(route('taskTypes.index'));
    }
}

resources/views/task_types/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Task Type</h3>
        </div>

        @include('adminlte-templates::common.errors')

        {!! Form::open(['route' => 'taskTypes.store']) !!}

        <div class="card-body">

            <div class="row">
                @include('task_types.fields')
            </div>

        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('taskTypes.index') }}" class="btn btn-default">Cancel</a>
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/task_types/datatables_actions.blade.php
{!! Form::open(['route' => ['taskTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('taskTypes.show', $id) }}" class='btn btn-default'>
        <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('taskTypes.edit', $id) }}" class='btn btn-default'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/task_types/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Edit Task Type</h3>
        </div>

        @include('adminlte-templates::common.errors')

        {!! Form::model($taskType, ['route' => ['taskTypes.update', $taskType->id], 'method' => 'patch']) !!}

        <div class="card-body">
            <div class="row">
                @include('task_types.fields')
            </div>
        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('taskTypes.index') }}" class="btn btn-default">Cancel</a>
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/task_types/fields.blade.php
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Task Name') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

resources/views/task_types/index.blade.php
@extends('layouts.app')

@section('content')

<div class="content">

    @include('flash::message')

    <div class="clearfix"></div>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Task Types</h3>
            <a class="btn-sm btn-primary float-right"
               href="{{ route('taskTypes.create') }}">
                <i class="fas fa-plus"></i>
            </a>
        </div>
        <div class="card-body">
            @include('task_types.table')
        </div>

    </div>
</div>

{{--    <div class="content px-3">--}}

{{--        @include('flash::message')--}}

{{--        <div class="clearfix"></div>--}}

{{--        <div class="card">--}}
{{--            <div class="card-body p-0">--}}
{{--                @include('task_types.table')--}}

{{--                <div class="card-footer clearfix">--}}
{{--                    <div class="float-right">--}}
{{--                        --}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--        </div>--}}
{{--    </div>--}}

@endsection

resources/views/task_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Task Type Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('taskTypes.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('task_types.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/task_types/show_fields.blade.php
<div class="col-sm-12">
    {!! Form::label('name', 'Name') !!}
    <p>{{ $taskType->name }}</p>
</div>

<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At') !!}
    <p>{{ $taskType->created_at }}</p>
</div>

<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At') !!}
    <p>{{ $taskType->updated_at }}</p>
</div>

resources/views/task_types/table.blade.php
@push('third_party_stylesheets')
    @include('layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush