routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('users', App\Http\Controllers\UserController::class);


Route::resource('hotelBranches', App\Http\Controllers\HotelBranchController::class);


Route::resource('roomTypes', App\Http\Controllers\RoomTypeController::class);


Route::resource('rooms', App\Http\Controllers\RoomController::class);


Route::resource('taskTypes', App\Http\Controllers\TaskTypeController::class);


Route::resource('tasks', App\Http\Controllers\TaskController::class);


Route::resource('bookings', App\Http\Controllers\BookingController::class);

Route::get('/availablebookroom/{id}/{check_in_date}/{check_out_date}','App\Http\Controllers\BookingController@availablebookroom')->name('availablebookroom');

Route::get('/availablerooms/{check_in_date}/{check_out_date}/{location}','App\Http\Controllers\BookingController@availablerooms')->name('availablerooms');

Route::resource('payments', App\Http\Controllers\PaymentController::class);

Route::get('generatereport/{start_date}/{end_date}/{hotel_id}','App\Http\Controllers\PaymentController@generatereport')->name('generatereport');

app/Http/Controllers/RoomTypeController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\RoomTypeDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateRoomTypeRequest;
use App\Http\Requests\UpdateRoomTypeRequest;
use App\Repositories\RoomTypeRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class RoomTypeController extends AppBaseController
{
    /** @var RoomTypeRepository $roomTypeRepository*/
    private $roomTypeRepository;

    public function __construct(RoomTypeRepository $roomTypeRepo)
    {
        $this->roomTypeRepository = $roomTypeRepo;
    }

    /**
     * Display a listing of the RoomType.
     *
     * @param RoomTypeDataTable $roomTypeDataTable
     *
     * @return Response
     */
    public function index(RoomTypeDataTable $roomTypeDataTable)
    {
        return $roomTypeDataTable->render('room_types.index');
    }

    /**
     * Show the form for creating a new RoomType.
     *
     * @return Response
     */
    public function create()
    {
        return view('room_types.create');
    }

    /**
     * Store a newly created RoomType in storage.
     *
     * @param CreateRoomTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateRoomTypeRequest $request)
    {
        $input = $request->all();

        $roomType = $this->roomTypeRepository->create($input);

        Flash::success('Room Type saved successfully.');

        return redirect(route('roomTypes.index'));
    }

    /**
     * Display the specified RoomType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $roomType = $this->roomTypeRepository->find($id);

        if (empty($roomType)) {
            Flash::error('Room Type not found');

            return redirect(route('roomTypes.index'));
        }

        return view('room_types.show')->with('roomType', $roomType);
    }

    /**
     * Show the form for editing the specified RoomType.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $roomType = $this->roomTypeRepository->find($id);

        if (empty($roomType)) {
            Flash::error('Room Type not found');

            return redirect(route('roomTypes.index'));
        }

        return view('room_types.edit')->with('roomType', $roomType);
    }

    /**
     * Update the specified RoomType in storage.
     *
     * @param int $id
     * @param UpdateRoomTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRoomTypeRequest $request)
    {
        $roomType = $this->roomTypeRepository->find($id);

        if (empty($roomType)) {
            Flash::error('Room Type not found');

            return redirect(route('roomTypes.index'));
        }

        $roomType = $this->roomTypeRepository->update($request->all(), $id);

        Flash::success('Room Type updated successfully.');

        return redirect(route('roomTypes.index'));
    }

    /**
     * Remove the specified RoomType from storage.
     *
     * @param int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $roomType = $this->roomTypeRepository->find($id);

        if (empty($roomType)) {
            Flash::error('Room Type not found');

            return redirect(route('roomTypes.index'));
        }

        $this->roomTypeRepository->delete($id);

        Flash::success('Room Type deleted successfully.');

        return redirect(route('roomTypes.index'));
    }
}

resources/views/room_types/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Create Room Type</h3>
        </div>

        @include('adminlte-templates::common.errors')

        {!! Form::open(['route' => 'roomTypes.store']) !!}

        <div class="card-body">

            <div class="row">
                @include('room_types.fields')
            </div>

        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('roomTypes.index') }}" class="btn btn-default">Cancel</a>
        </div>

        {!! Form::close() !!}

    </div>

@endsection

resources/views/room_types/datatables_actions.blade.php
{!! Form::open(['route' => ['roomTypes.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('roomTypes.show', $id) }}" class='btn btn-default'>
        <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('roomTypes.edit', $id) }}" class='btn btn-default'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/room_types/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Edit Room Type</h3>
        </div>

        @include('adminlte-templates::common.errors')


        {!! Form::model($roomType, ['route' => ['roomTypes.update', $roomType->id], 'method' => 'patch']) !!}

        <div class="card-body">
            <div class="row">
                @include('room_types.fields')
            </div>
        </div>

        <div class="card-footer">
            {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
            <a href="{{ route('roomTypes.index') }}" class="btn btn-default">Cancel</a>
        </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/room_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Name') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

resources/views/room_types/index.blade.php
@extends('layouts.app')

@section('content')

<div class="content">

    @include('flash::message')

    <div class="clearfix"></div>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Room Types</h3>
            <a class="btn-sm btn-primary float-right"
               href="{{ route('roomTypes.create') }}">
                <i class="fas fa-plus"></i>
            </a>
        </div>
        <div class="card-body">
            @include('room_types.table')
        </div>

    </div>
</div>

{{--    <div class="content px-3">--}}

{{--        @include('flash::message')--}}

{{--        <div class="clearfix"></div>--}}

{{--        <div class="card">--}}
{{--            <div class="card-body p-0">--}}
{{--                @include('room_types.table')--}}

{{--                <div class="card-footer clearfix">--}}
{{--                    <div class="float-right">--}}
{{--                        --}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}

{{--        </div>--}}
{{--    </div>--}}

@endsection

resources/views/room_types/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Room Type Details</h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('roomTypes.index') }}">
                        Back
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('room_types.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/room_types/show_fields.blade.php
<div class="col-sm-12">
    {!! Form::label('name', 'Name') !!}
    <p>{{ $roomType->name }}</p>
</div>

<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At') !!}
    <p>{{ $roomType->created_at }}</p>
</div>

<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At') !!}
    <p>{{ $roomType->updated_at }}</p>
</div>

resources/views/room_types/table.blade.php
@push('third_party_stylesheets')
    @include('layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('third_party_scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush