routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('users', App\Http\Controllers\UserController::class);


Route::resource('hotelBranches', App\Http\Controllers\HotelBranchController::class);


Route::resource('roomTypes', App\Http\Controllers\RoomTypeController::class);


Route::resource('rooms', App\Http\Controllers\RoomController::class);


Route::resource('taskTypes', App\Http\Controllers\TaskTypeController::class);


Route::resource('tasks', App\Http\Controllers\TaskController::class);


Route::resource('bookings', App\Http\Controllers\BookingController::class);

Route::get('/availablebookroom/{id}/{check_in_date}/{check_out_date}','App\Http\Controllers\BookingController@availablebookroom')->name('availablebookroom');

Route::get('/availablerooms/{check_in_date}/{check_out_date}/{location}','App\Http\Controllers\BookingController@availablerooms')->name('availablerooms');

Route::resource('payments', App\Http\Controllers\PaymentController::class);

Route::get('generatereport/{start_date}/{end_date}/{hotel_id}','App\Http\Controllers\PaymentController@generatereport')->name('generatereport');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>RAN HMS</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap4-toggle/3.6.1/bootstrap4-toggle.min.css"
          integrity="sha512-EzrsULyNzUc4xnMaqTrB4EpGvudqpetxG/WNjCpG6ZyyAGxeB6OBF9o246+mwx3l/9Cn838iLIcrxpPHTiygAA=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/css/adminlte.min.css"
          integrity="sha512-mxrUXSjrxl8vm5GwafxcqTrEwO1/oBNU25l20GODsysHReZo4uhVISzAKzaABH6/tTfAxZrY2FprmeAP5UZY8A=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/icheck-bootstrap/3.0.1/icheck-bootstrap.min.css"
          integrity="sha512-8vq2g5nHE062j3xor4XxPeZiPjmRDh6wlufQlfC6pdQ/9urJkU07NM0tEREeymP++NczacJ/Q59ul+/K2eYvcg=="
          crossorigin="anonymous"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css"
          integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw=="
          crossorigin="anonymous"/>

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css"
          integrity="sha512-aEe/ZxePawj0+G2R+AaIxgrQuKT68I28qh+wgLrcAJOz3rxCP+TwrK5SPN+E5I+1IQjNtcfvb96HDagwrKRdBw=="
          crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href="{{ url('css/custom.css') }}" />

    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    @stack('third_party_stylesheets')

    @stack('page_css')
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-white navbar-light {{\Illuminate\Support\Facades\Auth::user()->user_type == 'customer' ? 'mrgForCust' : ''}}">
        <ul class="navbar-nav">

            @if(\Illuminate\Support\Facades\Auth::user()->user_type != 'customer')
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            @endif

            @if(\Illuminate\Support\Facades\Auth::user()->user_type == 'customer')
                <li class="nav-item d-none d-sm-inline-block {{ Request::is('bookings*') ? 'active' : '' }}">
                    <a href="{{ route('bookings.index') }}" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block {{ Request::is('payments*') ? 'active' : '' }}">
                    <a href="{{ route('payments.index') }}" class="nav-link">Booking History</a>
                </li>
            @endif
        </ul>

        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown user-menu">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                    <img src="{!! asset('/images/user.png') !!}"
                         class="user-image img-circle elevation-2" alt="User Image">
                    <span class="d-none d-md-inline">{{ Auth::user()->name }}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <!-- User image -->
                    <li class="user-header bg-primary">
                        <img src="{!! asset('/images/user.png') !!}"
                             class="img-circle elevation-2"
                             alt="User Image">
                        <p>
                            {{ Auth::user()->name }}
                        </p>
                    </li>
                    <!-- Menu Footer-->
                    <li class="user-footer">
                        <a href="{{ route('users.edit', \Illuminate\Support\Facades\Auth::user()->id) }}" class="btn btn-default btn-flat">Profile</a>
                        <a href="#" class="btn btn-default btn-flat float-right"
                           onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Sign out
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    @if(\Illuminate\Support\Facades\Auth::user()->user_type != 'customer')
        @include('layouts.sidebar')
    @endif

    <div class="content-wrapper {{\Illuminate\Support\Facades\Auth::user()->user_type == 'customer' ? 'mrgForCust' : ''}}">
        <section class="content">
            @yield('content')
        </section>
    </div>

   <footer class="main-footer {{\Illuminate\Support\Facades\Auth::user()->user_type == 'customer' ? 'mrgForCust' : ''}}">
        <strong>
           Copyright &copy; 2022 RAN HMS.
        </strong>
        All rights reserved.
    </footer>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/js/adminlte.min.js"
        integrity="sha512-AJUWwfMxFuQLv1iPZOTZX0N/jTCIrLxyZjTRKQostNU71MzZTEPHjajSK20Kj1TwJELpP7gl+ShXw5brpnKwEg=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"
        integrity="sha512-qTXRIMyZIFb8iQcfjXWCO8+M5Tbc38Qi5WzdPOYZHIlZpzBHG3L3by84BBBOiRGiEb7KKtAOAs5qYdUiZiQNNQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"
        integrity="sha512-GDey37RZAxFkpFeJorEUwNoIbkTwsyC736KNSYucu1WJWFK9qTdzYub8ATxktr6Dwke7nbFaioypzbDOQykoRg=="
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"
        integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A=="
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-switch/1.3/bootstrapSwitch.min.js"
        integrity="sha512-DAc/LqVY2liDbikmJwUS1MSE3pIH0DFprKHZKPcJC7e3TtAOzT55gEMTleegwyuIWgCfOPOM8eLbbvFaG9F/cA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
    $(function () {
        bsCustomFileInput.init();
    });

    $("input[data-bootstrap-switch]").each(function () {
        $(this).bootstrapSwitch('state', $(this).prop('checked'));
    });
</script>

@stack('third_party_scripts')

@stack('page_scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<link href="https://cdn.datatables.net/1.10.25/css/dataTables.bootstrap4.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.2/css/buttons.bootstrap4.min.css">

resources/views/layouts/datatables_js.blade.php
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.2/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
@if(\Illuminate\Support\Facades\Auth::user()->user_type == 'admin' ||
 \Illuminate\Support\Facades\Auth::user()->user_type == 'manager' ||
 \Illuminate\Support\Facades\Auth::user()->user_type == 'customer')
    <li class="nav-item">
        <a href="{{ route('bookings.index') }}"
           class="nav-link {{ Request::is('bookings*') ? 'active' : '' }}">
            <i class="nav-icon fas fa-shopping-cart"></i>
            <p>Bookings</p>
        </a>
    </li>
@endif

@if(\Illuminate\Support\Facades\Auth::user()->user_type == 'admin' || \Illuminate\Support\Facades\Auth::user()->user_type == 'manager')
<li class="nav-item">
    <a href="{{ route('users.index') }}"
       class="nav-link {{ Request::is('users*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-user"></i>
        <p>{{\Illuminate\Support\Facades\Auth::user()->user_type == 'admin'? 'Users' : 'Staff'}}</p>
    </a>
</li>
@endif

@if(\Illuminate\Support\Facades\Auth::user()->user_type == 'admin')
<li class="nav-item">
    <a href="{{ route('hotelBranches.index') }}"
       class="nav-link {{ Request::is('hotelBranches*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-hotel"></i>
        <p>Hotels</p>
    </a>
</li>
@endif

@if(\Illuminate\Support\Facades\Auth::user()->user_type == 'admin' ||
\Illuminate\Support\Facades\Auth::user()->user_type == 'manager')
<li class="nav-item">
    <a href="{{ route('rooms.index') }}"
       class="nav-link {{ Request::is('rooms*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-bed"></i>
        <p>Rooms</p>
    </a>
</li>
@endif

@if(\Illuminate\Support\Facades\Auth::user()->user_type == 'admin' ||
\Illuminate\Support\Facades\Auth::user()->user_type == 'manager' ||
\Illuminate\Support\Facades\Auth::user()->user_type == 'staff')
<li class="nav-item">
    <a href="{{ route('tasks.index') }}"
       class="nav-link {{ Request::is('tasks*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-tasks"></i>
        <p>Tasks</p>
    </a>
</li>
@endif

@if(\Illuminate\Support\Facades\Auth::user()->user_type == 'admin')
<li class="nav-item">
    <a href="{{ route('payments.index') }}"
       class="nav-link {{ Request::is('payments*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-file"></i>
        <p>Report</p>
    </a>
</li>
@endif

@if(\Illuminate\Support\Facades\Auth::user()->user_type == 'admin')
<li class="nav-item {{ Request::is('taskTypes*') || Request::is('roomTypes*') ? 'menu-is-opening menu-open' : '' }}">
    <a href="#" class="nav-link {{ Request::is('taskTypes*') || Request::is('roomTypes*') ? 'active' : '' }}">
        <i class="nav-icon fas fa-cog"></i>
        <p>
            Settings
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>
    <ul class="nav nav-treeview" style="display: {{ Request::is('taskTypes*') || Request::is('roomTypes*') ? 'block' : 'none' }};">
        <li class="nav-item">
            <a href="{{ route('taskTypes.index') }}"
               class="nav-link {{ Request::is('taskTypes*') ? 'active' : '' }}">
                <i class="nav-icon fas fa-bars"></i>
                <p>Task Types</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{ route('roomTypes.index') }}"
               class="nav-link {{ Request::is('roomTypes*') ? 'active' : '' }}">
                <i class="nav-icon fas fa-bed"></i>
                <p>Room Types</p>
            </a>
        </li>
    </ul>
</li>
@endif

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="{{ url('/home') }}" class="brand-link">
{{--        <img src="{!! asset('/images/logo.png') !!}"--}}
{{--             alt="{{ config('app.name') }} Logo"--}}
{{--             class="brand-image elevation-3" style="border-radius: 20%">--}}
        <span class="brand-text font-weight-light">RAN HMS</span>
    </a>
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                @include('layouts.menu')
            </ul>
        </nav>
    </div>
</aside>